### ISSUE TITLE
Key difference with mobx-state-tree

### ISSUE THREAD

**Issue by muhajirdev** [ForsakenHarmony/parket#25]
Hi,
Very interesting lib, I'd love to know the key difference between parket and mobx-state-tree.

One thing I notice is that parket doesn't need use `flow` for async.

Would love to know more difference, such as devtools, pattern, etc.

**Comment by ForsakenHarmony** [comment]
Basically it's a smaller version, which also means it has a couple less features

For example fields aren't typed, so you can assign whatever you want, but this also means that for deserialization into a type it needs a specific field

There's no reference field, but you could maybe do that with a computed property

If you're interested you should also take a look at the pre release which simplified the API (might still have to change it to a class because typing doesn't work very well)
